"""Add cascade delete to reviews

Revision ID: b1ac02b0be46
Revises: a76c28e8db14
Create Date: 2024-07-23 20:15:06.514001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ac02b0be46'
down_revision = 'a76c28e8db14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=13),
               existing_nullable=True)

    # ### end Alembic commands ###
